FROM python:3.11-slim

WORKDIR /app
COPY src/platform/requirements_dashboard.txt .
RUN pip install --no-cache-dir -r requirements_dashboard.txt

COPY src/platform/ ./platform/

CMD ["streamlit", "run", "platform/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
